/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_xujinliang_decview_DecView */

#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_xujinliang_decview_DecView
 * Method:    Decorate
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_xujinliang_decview_DecView_Decorate
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
